export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_USER_PROFILE_START = 'EDIT_USER_PROFILE_START';
export const EDIT_USER_PROFILE_FAILED = 'EDIT_USER_PROFILE_FAILED';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';
