export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const ERROR_GETTING_RECIPES = 'ERROR_GETTINGZ-RECIPES';
export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const DELETE_USER_RECIPE = 'DELETE_USER_RECIPE';
export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
export const ADD_NEW_REVIEW = 'ADD_NEW_REVIEW';
export const GET_RECIPE_REVIEW = 'GET_RECIPE_REVIEW';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_FAVORITES = 'GET_USER_FAVORITES';
export const REMOVED_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const GET_SINGLE_RECIPE = 'GET_SINGLE_RECIPE ';
export const GET_SINGLE_RECIPE_REVIEWS = 'GET_SINGLE_RECIPE_RECIEWS';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

