export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAILED_ERRORS = 'LOGIN_FAILED_ERRORS';
export const SIGNUP_FAILED_ERRORS = 'SIGNUP_FAILED_ERRORS';

